/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// using an FPU for this OS
#include "lcd/screenDriver.h"
#include "general/mcuHeader.h"
#include "programs/bootScreen.h"
#include "programs/terminal/terminal.h"
#include "flash/flashManager.h"
#include "general/allocator.h"
#include "programs/fileViewer.h"
#include "keyboard/ps-2Interface.h"

int main(void)
{
	SystemInit();
	pinout();
	initHeap();
	unlockFlash();
	setPsize();

	// main loop for OS
	LCD_INIT();
	clearLCD();
	changeColor(0xFFFF);
	//resetFlash();
	allocMetadataBuf();
	initKeyboardInterface();
	//putString("Hello! This is an OS for the\nSTM32F407VGT6-DISC1.\n\n\nIt is completely BARE METAL,  no libraries or external\n headers ;)\n\n\nIt contains:a screen driver(for elegoo 2.8in tft lcd),ps-2 keyboard driver,and a system for storing/writing/running programs :)", 250);

	// test
	//addFlashPkg(64*3, 'a');
	//printNum(*((volatile uint32_t*)FLASHUSED));
	//const char* wr = "bbbaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\naaaaaaa\n";
	//writeToPkg('a', (uint32_t*)wr);
	//displayFileTxt('a');
	//startupScreen();
	//beginTerminal();
	//saveMetaBuffer();
	while(1){
		//speakerCycle();
	}
	for(;;);
}
